export const FORM_DATA_FETCH_SUCCEEDED = 'FORM_DATA_FETCH_SUCCEEDED'

/**
 * BUILDINGS
 */
export const BUILDINGS_FAILED = 'BUILDINGS_FAILED'

export const BUILDINGS_FETCH_SUCCEEDED = 'BUILDINGS_FETCH_SUCCEEDED'
export const BUILDINGS_FETCH_REQUESTED = 'BUILDINGS_FETCH_REQUESTED'

export const REMOVE_BUILDING_SUCCEEDED = 'REMOVE_BUILDING_SUCCEEDED'
export const REMOVE_BUILDING_REQUESTED = 'REMOVE_BUILDING_REQUESTED'

export const ADD_BUILDING_SUCCEEDED = 'ADD_BUILDING_SUCCEEDED'
export const EDIT_BUILDING_SUCCEEDED = 'EDIT_BUILDING_SUCCEEDED'
export const SAVE_BUILDING_REQUESTED = 'SAVE_BUILDING_REQUESTED'

export const BUILDING_FETCH_SUCCEEDED = 'BUILDING_FETCH_SUCCEEDED'
export const BUILDING_FETCH_REQUESTED = 'BUILDING_FETCH_REQUESTED'
export const RESET_BUILDING = 'RESET_BUILDING'
export const EDIT_BUILDING = 'EDIT_BUILDING'

/**
 * ROOMS
 */
export const ROOM_TYPES_FETCH_REQUESTED = 'ROOM_TYPES_FETCH_REQUESTED'
export const ROOM_TYPES_FETCH_SUCCEEDED = 'ROOM_TYPES_FETCH_SUCCEEDED'

export const EDIT_ROOM_TYPE_SUCCEEDED = 'EDIT_ROOM_TYPE_SUCCEEDED'
export const SAVE_ROOM_TYPE_REQUESTED = 'SAVE_ROOM_TYPE_REQUESTED'

export const ROOM_TYPE_FETCH_SUCCEEDED = 'ROOM_TYPE_FETCH_SUCCEEDED'
export const ROOM_TYPE_FETCH_REQUESTED = 'ROOM_TYPE_FETCH_REQUESTED'
export const RESET_ROOM_TYPE = 'RESET_ROOM_TYPE'
export const EDIT_ROOM_TYPE = 'EDIT_ROOM_TYPE'

export const REMOVE_ROOM_TYPE_REQUESTED = 'REMOVE_ROOM_TYPE_REQUESTED'
export const REMOVE_ROOM_TYPE_SUCCEEDED = 'REMOVE_ROOM_TYPE_SUCCEEDED'
export const ROOM_TYPES_FAILED = 'ROOMTYPES_FAILED'

export const ROOM_OPTIONS_FETCH_REQUESTED = 'ROOM_OPTIONS_FETCH_REQUESTED'
export const ROOM_OPTIONS_FETCH_SUCCEEDED = 'ROOM_OPTIONS_FETCH_SUCCEEDED'

export const EDIT_ROOM_OPTION_SUCCEEDED = 'EDIT_ROOM_OPTION_SUCCEEDED'
export const SAVE_ROOM_OPTION_REQUESTED = 'SAVE_ROOM_OPTION_REQUESTED'

export const ROOM_OPTION_FETCH_SUCCEEDED = 'ROOM_OPTION_FETCH_SUCCEEDED'
export const ROOM_OPTION_FETCH_REQUESTED = 'ROOM_OPTION_FETCH_REQUESTED'
export const RESET_ROOM_OPTION = 'RESET_ROOM_OPTION'
export const EDIT_ROOM_OPTION = 'EDIT_ROOM_OPTION'

export const REMOVE_ROOM_OPTION_REQUESTED = 'REMOVE_ROOM_OPTION_REQUESTED'
export const REMOVE_ROOM_OPTION_SUCCEEDED = 'REMOVE_ROOM_OPTION_SUCCEEDED'
export const ROOM_OPTIONS_FAILED = 'ROOM_OPTIONS_FAILED'
